hw4 (res) + minor updates
VovaMiller/android-course-2019 pull request #4
Opened 2019-10-18 18:40 UTC by VovaMiller

2019-10-19 20:39 UTC, IvanShafran requested changes
Всё как надо сделал) Попробуй ScrollView убрать, как в комменте описано

2019-10-19 20:39 UTC, IvanShafran commented on app/src/main/res/layout/activity_info.xml
> +    <ScrollView
В TextView уже есть функционал скроллинга. Попробуй: https://stackoverflow.com/a/3256305/7958563

2019-10-19 21:09 UTC, VovaMiller commented on app/src/main/res/layout/activity_info.xml
> +    <ScrollView
У меня так и было реализовано раньше, но я хотел, чтобы скроллинг с инерцией был, чтобы, например, в конец или начало текста можно было резким движением пальца попасть. А скроллинг что в TextView какой-то топорный, через весь текст приходится пальцем елозить.
На stackoverflow прочитал, что "инерции" по умолчанию в TextView не предусмотрено и как раз предлагали обернуть в ScrollView.
Если это принципиально, верну как было. Просто хотел как лучше)

2019-10-20 08:26 UTC, VovaMiller commented
Так что, мне обязательно убирать ScrollView?

2019-10-20 13:37 UTC, IvanShafran commented on app/src/main/res/layout/activity_info.xml
> +    <ScrollView
Оки

2019-10-20 13:38 UTC, IvanShafran approved these changes

2019-10-20 13:38 UTC, merged