hw5 (Fragments)
VovaMiller/android-course-2019 pull request #5
Opened 2019-11-01 11:24 UTC by VovaMiller

2019-11-02 13:52 UTC, IvanShafran requested changes
Отличная работа)
Посмотри, пожалуйста, мои комментарии

2019-11-02 13:52 UTC, IvanShafran commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
А для каких зависимостей эта штука нужна?

2019-11-02 13:52 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/ListFragment.java
> +    public ListFragment() {}
У Java класса, если не указан конструктор, то будет пустой по умолчанию.
Поэтому это можно убрать

2019-11-02 13:52 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +            if (!isPhone && (noteId.length() > 0)) {
Сравнение noteId с null выглядело бы более естественным чем с пустой строкой, имхо

2019-11-02 13:52 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +    private void laptopOrientationChanged() {
Проверил -- всё работает. Это круто)
Но код немного переусложненным для меня выглядит. Кажется, что фрагмент ListFragment не надо пересоздавать каждый раз. Достаточно Info перекладывать
Попробуешь упростить?

2019-11-02 16:08 UTC, VovaMiller commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Не знаю, случайно здесь появилось

2019-11-02 16:10 UTC, VovaMiller commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +    private void laptopOrientationChanged() {
Понятия не имею, зачем ListFragment пересоздавал. Видимо, понесло

2019-11-02 16:20 UTC, VovaMiller commented
А легально было бы поставить два FrameLayout и в портрете (Заметка поверх Списка) и в landscape (Список слева, Заметка справа), для FrameLayout Заметки по умолчанию поставить visibility=gone, и при открытии заметки менять на visibility=visible? Тогда как минимум не пришлось бы возиться с переподцеплением фрагмента с контейнера на контейнер.

2019-11-03 13:49 UTC, IvanShafran commented
Слушай, да) Кажется, два FrameLayout сработает. И даже visibility менять не надо, думаю. FrameLayout и так прозрачный сам по себе

2019-11-03 14:23 UTC, IvanShafran requested changes

2019-11-03 14:23 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +public class HostActivity extends AppCompatActivity implements EventListener {
Да, я походу зря вас мучал с разным количестом FrameLayout-ов.
Посмотри ветку hw5-easy-way у себя. Я там накидал работу с двумя FrameLayout-ами.
Потестил. Вроде, всё работает.
Используешь это?

2019-11-03 14:24 UTC, IvanShafran commented
Кстати, на каком сайте ты нарезал картинки на разные разрешения?

2019-11-03 15:15 UTC, VovaMiller commented
> Слушай, да) Кажется, два FrameLayout сработает. И даже visibility менять не надо, думаю. FrameLayout и так прозрачный сам по себе

Точно, не нужно. Я когда проверял, реально ли так сдалать, разметку с планшета скопировал, а там в корне был LinearLayout, а с ним без изменения visivility не получается.

2019-11-03 15:15 UTC, VovaMiller commented
> Кстати, на каком сайте ты нарезал картинки на разные разрешения?

Сам скрипт написал. Внутри использовал **ffmpeg**.

2019-11-03 15:16 UTC, VovaMiller commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +public class HostActivity extends AppCompatActivity implements EventListener {
Да

2019-11-03 15:39 UTC, merged