hw7 (AsyncTask + Save Button) + improvements
VovaMiller/android-course-2019 pull request #7
Opened 2019-11-11 21:58 UTC by VovaMiller

2019-11-16 15:48 UTC, IvanShafran requested changes
Супер работа 👍 
Поправь замечания:
- про работу в фоне с картинками
- про лишнее поле для контекста
- про лямбды

Остальные можно не править

2019-11-16 15:48 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/AppUtils.java
> +    public static Bitmap getBitmap(String path) {
Я не предполагал, что картинки в этом ДЗ показывать надо, если честно....
Круто, что разобрался сам, но для показа лучше использовать Picasso или Glide или Fresco библиотеки. Они всё делают за нас: загрузка, поворот, работа в фоне, уменьшение картинки

2019-11-16 15:48 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/AppUtils.java
> +    public static Bitmap getBitmap(String path) {
В этом PR можно оставить как есть. В рамках 8-го дз надо будет перевести на Picasso, например

2019-11-16 15:48 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +        this.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);
Также можно это в манифесте указать:
https://stackoverflow.com/a/18977480/7958563

2019-11-16 15:48 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +        fab.setOnClickListener(new View.OnClickListener() {
Т.к. ты используешь 1.8 java compatibility, то можно лямбды использовать:
```
fab.setOnClickListener(view -> onClickFAB());
```

2019-11-16 15:48 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +    public boolean onCreateOptionsMenu(Menu menu) {
В целом сойдёт. Переделывать не надо
Но лучше меню показывать там, где оно используется. Внутри фргмента. При переключении фрагментов Acitivty само скрывает и показывает меню фрагментов

2019-11-16 15:48 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/TaskFragment.java
> +    private Context mContext;
Иметь отдельное поле для Context-а не надо. У фрагмента есть метод getContext()/requireContext()

2019-11-16 15:48 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/CameraActivity.java
> +    private File saveCompressedCopy(@NonNull final File file) {
Этот метод надо в фоне тоже делать, т.к. работа загрузка/уменьшение картинки -- долгие операции

2019-11-19 09:46 UTC, IvanShafran approved these changes

2019-11-19 09:46 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/AppUtils.java
> +    public static File saveCompressedCopy(@NonNull final File file,
Вспомнил важный момент. Тебе не надо пережимать картинку. Для показа картинки в UI ты будешь использовать Picasso, он при загрузке сам всё сделает. А большая картинка нужная для распознавания текста на ней
Поэтому тебе вся работа с поворотами не нужна, думаю

Я PR заапрувлю, но для 8-ой домашки это надо будет убрать и упростить

2019-11-19 09:46 UTC, merged

2019-11-19 11:16 UTC, VovaMiller commented
@IvanShafran 
Как только Picasso поставил собирался удалить saveCompressedCopy, но без него картинки в меню со списком заметок загружаются ощутимо дольше, по крайней мере при старте приложения. Такое ощущение, что Picasso не кэширует эти маленькие картинки на внутреннее хранилище, а способа его заставить это делать не нашёл.
А по поводу поворотов. Мне так или иначе нужно запомнить информацию о том, в какой ориентации была сделана фотография. Будет ли лучше, если я не буду трогать метаданные фотографии, а сохраню информацию об ориентации прямо в заметке (и в БД, соответственно) и при каждом отображении картинки будут указывать Picasso как её нужно повернуть?

2019-11-19 13:31 UTC, IvanShafran commented
@VovaMiller у тебя в файле(который CameraView записала) эти метаданные уже должны быть. Потом их можно считать руками.
Про Picasso странно это слышать. Надо будет посмотреть дополнительно. Сейчас сказать ничего не могу

2019-11-19 13:44 UTC, VovaMiller commented
@IvanShafran 
У меня на активити с камерой заблокирована смена ориентации - стоит портретная (мне не нравилось, что камера при каждом перевороте пересоздавалась), поэтому, как я понял, в метаданные всегда пишется, что фото сделано в портретной ориентации и мне приходится изменять это вручную.