hw9 (PopupMenu)
VovaMiller/android-course-2019 pull request #9
Opened 2019-11-22 13:13 UTC by VovaMiller

Помимо непосредственно задания#9 избавился от ручной модификации EXIF метаданных получаемых фото, разблокировав смену ориентации для активити камеры.
Тем самым теперь при снимке нужная информация о повороте записывается сама.
Вообще, мне хотелось, чтобы при повороте экрана совсем не чувствовалось, что пересоздаётся объект камеры, поэтому изначально заблокировал смену ориентации и сам отслеживал угол поворота девайса, однако это оказалось совсем не тривиально. На первый взгляд работало как надо, но недавно вот попробовал сделать снимок листа, лежащего на столе, так камера ни в какую не хотела снимать в landscape, возвращая меня в portrait как только навожу на лист. Так что в рамках pet-проекта решил не усложнять.

2019-11-22 13:14 UTC, VovaMiller commented
Хотел ещё изменить ширину PopupMenu, т.к. выглядит он избыточно широким, но никакого доступного способа не нашёл.

2019-11-23 18:42 UTC, IvanShafran commented
Я тоже не нагуглил как нормально размер его менять. Везде хаки странные.
Про поворот экрана не могу порекомендовать тоже. Всегда поворот обрабатывал, а не запрещал

2019-11-23 19:04 UTC, IvanShafran requested changes
Предлагаю вынести из HostActivity код ближе к ViewHolder и фрагменту списка заметок

2019-11-23 19:04 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/CameraActivity.java
>      protected void onDestroy() {
Можно убрать тогда, раз метод пустой

2019-11-23 19:04 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/DeleteDialogFragment.java
> +    private long noteId;
После поворота экрана id будет нулем. Так что удалится либо ничего, либо самая первая заметка вместо нужной

2019-11-23 19:04 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +    public void onPostExecuteDeleteNote() {
Реагировать на каждое событие тоже рабочий вариант. Но более удобный с моей точки зрения вариант, когда есть одна точка получения событий о новых данных и методы для изменения. Если нужна реакция на отдельные события изменения, то ещё доп колбеки на них. Но обычно достаточно одного слушателя на все данные.
```
class NoteStorage {
   interface Listener {
       void onNotes(List<Note> notes);
   }
   void registerListener(Listener listener);
    void unregisterListener(Listener listener);
    void delete(id);
    void insert(...);
     void update(....);
}

2019-11-23 19:04 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +    public void onButtonMoreClicked(View view, long id) {
Делать все через HostActivity плохой вариант. Если у тебя большое приложение с кучей экранов, то HostActivity будет ад на тысячи строк.
Клик на More можно отработать сразу во ViewHolder.
Клик на share там же или во фрагменте. Во ViewHolder можно хранить объект Note и оттуда текст брать.
Клик на удалить можно провести через фрагмент, а уже потом когда пользователь согласится, то вызвать у HostActivity метод, который отработает в TasksFragment

2019-11-24 11:53 UTC, VovaMiller commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +    public void onPostExecuteDeleteNote() {
Не совсем понял. То есть вместо:
`    public interface TaskCallbacks {
        void onPostExecuteNewNote();
        void onPostExecuteUpdateText(boolean failed);
        void onBitmapLoaded(long lastModified, final String imgPath, final Bitmap bitmap);
        void onTextRecognized(long lastModified, final String imgPath, final String text);
        void onPostExecuteDeleteNote();
        void onNoteTextExtracted(final int code, final String text);
    }`
сделать
`    public interface TaskCallbacks {
        void onNotes();
    }`
?
 А как быть с передаваемыми аргументами, класть их в какой-нибудь Bundle?

2019-11-24 19:19 UTC, IvanShafran commented on app/src/main/java/com/vovamiller_97/pioneer/HostActivity.java
> +    public void onPostExecuteDeleteNote() {
Не, это относилось только к методам заметки.
Если очень обобщенно то есть статьи про Uni directional flow:
https://proandroiddev.com/unidirectional-data-flow-on-android-the-blog-post-part-1-cadcf88c72f5

Если кратко, то я имел в виду, что можно сделать подписку на состояние заметок. Как только что-то изменилось в списке заметок, то новые заметки сами приходят в подписку, а не по запросу.
Это очень удобно, т.к. заметки можно менять из любого места, а изменения автоматически подтянутся туда, где это надо.

2019-11-27 20:10 UTC, IvanShafran approved these changes

2019-11-27 20:10 UTC, merged